alisw/alisw.github.io

infrastructure-frontend.markdown, infrastructure-jenkins.markdown, infrastructure-mesos.markdown
Add instructions to register machines with proper owner / mainuser.
=> Improve instructions to spawn machines.

git-advanced.markdown, git-tutorial.markdown
Small typo and grammar fixes, and fixing broken links
=> Make minor amendments to the git pages

git-advanced.markdown
In response to Dario's comment over at https://alice.its.cern.ch/jira/browse/ALIROOT-7127
I believe that a good ui can do wonders in understanding git and improving the workflow with it. Naturally, everybody having settle on a UI might lack overview. I settled on Emacs+magit, and thus don't feel confident recommending many other plug-ins without having tried them. More additions to the list are of course welcome.
=> Added section about git UI

_layouts/main.html
@ktf, @brinick: currently all links are opened in new tabs/windows, this PR fixes that.
=> Do not open all links in new tabs/windows

infrastructure-macos.markdown, infrastructure-pr-testing.markdown, infrastructure.markdown
Add documentation on how to setup macOS builders and how to run CI checkers on macOS.
=> O2-1031 macOS CI Documentation

infrastructure-alibi-user-guide.markdown, infrastructure.markdown
A quickstart guide for ALIBI users
=> O2 939 alibi documentation

infrastructure-pr-testing.markdown
- Added a link to an example of creating a new checker for o2-dataflow
- Fixed the anchor links in the list of subsections
=> Update Pull Request Builders section:

infrastructure-nightly.markdown
Fixed the link to the results of the builds web page
=> Updated Nightly Builds section:

infrastructure-auto-builds.markdown, infrastructure.markdown
This is a first draft; I'm not sure about the stuff to be done in Jenkins.
=> Draft docs on setting up automatic release builds

infrastructure-rpms.markdown
Trying to centralise documentation which is sparse in different places.
=> Reworked documentation for the RPMs

infrastructure-pr-testing.markdown
=> Updated Pull Request Builders page:

infrastructure-release-process.md
The new links allow directly starting the action again.
=> Use new-style GitHub action links

faq.markdown, git-advanced.markdown, git-tutorial.markdown
Related PRs:
* https://github.com/alisw/alibuild/pull/691
* https://github.com/alice-doc/alice-analysis-tutorial/pull/128
=> Use standard names of remotes.

infrastructure-release-process-o2.md, infrastructure-release-process.md, infrastructure.markdown
Hi @ihrivnac 
I added a page for the O2PDPSuite release process. Please let me know if this is OK like that.
Cheers,
Ole
=> Add O2PDPSuite release proccess documentation

infrastructure-o2-branches.md
@chiarazampolli I think this is what you meant -- let me know if I misunderstood!
=> Document versioning scheme for updating old O2 tags

infrastructure-macos.markdown
Make certificate requests on mac more automated
=> Make certificate requests on mac more automated

infrastructure-macos.markdown
Fix REMOTE_WORK_DIR everywhere
=> Fix REMOTE_WORK_DIR everywhere

infrastructure-macos.markdown
Cleanup download area before we begin
=> Cleanup download area before we begin

infrastructure-macos.markdown
Ask for password correctly
---
[//]: # (BEGIN SAPLING FOOTER)
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/alisw/alisw.github.io/pull/117).
* #118
* __->__ #117
=> Ask for password correctly

infrastructure-macos.markdown
=> Provide password via security

infrastructure-macos.markdown
=> Improve test

infrastructure-macos.markdown
=> Add list of post-mortems

docs/infrastructure-nomad.md
Also fixing the headers, the table of contents wasn't rendering properly
=> Add nomad system gc to troubleshooting

docs/infrastructure-nightly.md
=> Add some info about daily tags debugging

docs/infrastructure-macos.md
This issue happens very often when they reboot, might as well have it in the docs
=> Add macOS nomad troubleshooting info

docs/infrastructure-docker-packer.md
To be merged with https://github.com/alisw/docks/pull/277
=> Update pushing Docker images instructions

docs/infrastructure-macos.md
Lessons learned from the M4 cluster
=> Modernize instructions for Mac setup
